name: Package Application with Pyinstaller

on: 
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Package Application
      uses: walmis/pyinstaller-action-windows@main
      with:
        path: .
       
